"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = [
    ('database', ['database/db.py']),
    ('views', [
        'views/dashboard.py',
        'views/snapshot_entry.py',
        'views/expenses.py',
        'views/charts.py',
        'views/notes.py',
        'views/help.py',
        'views/__init__.py',
    ]),
    ('models', [
        'models/snapshot.py',
        'models/expense.py',
        'models/__init__.py',
    ]),
]
OPTIONS = {
    'argv_emulation': False,
    'packages': [
        'customtkinter',
        'matplotlib',
        'numpy',
        'PIL',
        'darkdetect',
    ],
    'includes': [
        'tkinter',
        'sqlite3',
    ],
    'excludes': [
        'pyapp',
    ],
    'plist': {
        'CFBundleName': 'Money Tracker',
        'CFBundleDisplayName': 'Money Tracker',
        'CFBundleVersion': '1.0.0',
        'CFBundleShortVersionString': '1.0.0',
        'NSHighResolutionCapable': True,
    },
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)